name: "Info Block"
description: "Print runner OS/hardware/network details for debugging"
author: "medyagh"
inputs:
  fail_on_error:
    description: "Set to true to fail the step if any command errors."
    required: false
    default: "false"
outputs:
  memory_gb:
    description: "Total memory in gigabytes (integer)"
    value: ${{ steps.info-block.outputs.memory_gb }}
  cpu_cores:
    description: "Number of CPU cores (integer)"
    value: ${{ steps.info-block.outputs.cpu_cores }}
  load_average:
    description: "Load average (1-minute on macOS/Linux, current CPU load % on Windows)"
    value: ${{ steps.info-block.outputs.load_average }}
  free_mem:
    description: "Free/available memory in megabytes (integer)"
    value: ${{ steps.info-block.outputs.free_mem }}
  procs:
    description: "List of running processes on the runner"
    value: ${{ steps.info-block.outputs.procs }}
  duration_seconds:
    description: "Runtime of the info-block action in seconds"
    value: ${{ steps.info-block.outputs.duration_seconds }}
runs:
  using: "composite"
  steps:
    - name: Print runner details
      id: info-block
      shell: bash
      run: bash "${GITHUB_ACTION_PATH}/scripts/info-block.sh" "${{ inputs.fail_on_error }}"
