name: "Info Block"
description: "Print runner OS/hardware/network details for debugging"
author: "medyagh"
inputs:
  fail_on_error:
    description: "Set to true to fail the step if any command errors."
    required: false
    default: "false"
outputs:
  memory_gb:
    description: "Total memory in gigabytes (integer)"
    value: ${{ steps.info-block.outputs.memory_gb }}
  load_average:
    description: "Load average (1-minute on macOS/Linux, current CPU load % on Windows)"
    value: ${{ steps.info-block.outputs.load_average }}
runs:
  using: "composite"
  steps:
    - name: Print runner details
      id: info-block
      shell: bash
      run: bash "${GITHUB_ACTION_PATH}/scripts/info-block.sh" "${{ inputs.fail_on_error }}"
