name: "Info Block"
description: "Print runner OS/hardware/network details for debugging"
author: "medyagh"
runs:
  using: "composite"
  steps:
    - name: Print runner details
      shell: bash
      run: |
        set -uo pipefail
        echo "=== Info Block for $RUNNER_OS ==="

        if [[ "$RUNNER_OS" == "macOS" ]]; then
          set -x
          echo "=== Kernel and OS ==="
          uname -a
          sw_vers
          sysctl kern.osrelease kern.osversion kern.version || true

          echo "=== CPU ==="
          sysctl -n machdep.cpu.brand_string
          sysctl -n hw.ncpu
          sysctl -n machdep.cpu.core_count || true
          sysctl -n machdep.cpu.thread_count || true
          sysctl -n machdep.cpu.features || true
          sysctl -n machdep.cpu.leaf7_features || true
          sysctl -n machdep.cpu.extfeatures || true

          echo "=== Memory ==="
          sysctl -n hw.memsize
          echo "$(sysctl -n hw.memsize) / 1024 / 1024 / 1024" | bc
          sysctl -n hw.pagesize || true
          vm_stat || true

          echo "=== Virtualization ==="
          sysctl -n kern.hv_vmm_present || true
          sysctl -n kern.hv_support || true
          sysctl -n machdep.cpu.features | grep -i vmx || true

          echo "=== Hardware Inventory ==="
          sysctl hw.model
          system_profiler SPHardwareDataType

          echo "=== Storage ==="
          diskutil list || true
          df -h
          system_profiler SPStorageDataType | sed -n '1,200p' || true

          echo "=== Network ==="
          echo "${HTTP_PROXY:-}"
          ifconfig
          networksetup -listallhardwareports || true
          scutil --get HostName || true
          scutil --get LocalHostName || true
          scutil --get ComputerName || true
          route -n get default || true
          netstat -rn || true
          scutil --dns || true

          echo "=== Uptime and Load ==="
          uptime
          sysctl kern.boottime || true
          top -l 1 -n 0 | head -n 10 || true

          echo "=== Security ==="
          spctl --status || true
          csrutil status || true
        elif [[ "$RUNNER_OS" == "Linux" ]]; then
          set -x
          echo "=== Kernel and OS ==="
          uname -a
          cat /etc/os-release

          echo "=== CPU ==="
          nproc
          grep -m1 'model name' /proc/cpuinfo || true
          grep -m1 '^flags' /proc/cpuinfo || true
          lscpu || true
          lscpu | grep -i 'hypervisor\|virt' || true

          echo "=== Memory ==="
          grep MemTotal /proc/meminfo || true
          awk '/MemTotal/ {printf "%.2f\n", $2 / 1024 / 1024}' /proc/meminfo || true
          free -h || true

          echo "=== Virtualization ==="
          systemd-detect-virt || true
          egrep -c '(vmx|svm)' /proc/cpuinfo || true
          lsmod | grep -E '(^kvm|kvm_(intel|amd))' || true
          if [ -f /sys/module/kvm_intel/parameters/nested ]; then
            echo -n "kvm_intel nested: "; cat /sys/module/kvm_intel/parameters/nested
          fi
          if [ -f /sys/module/kvm_amd/parameters/nested ]; then
            echo -n "kvm_amd nested: "; cat /sys/module/kvm_amd/parameters/nested
          fi
          sudo journalctl -k | grep -i kvm | tail -n 100 || true
          if command -v virt-host-validate >/dev/null 2>&1; then
            sudo virt-host-validate || true
          fi

          echo "=== Hardware Inventory ==="
          sudo dmidecode -s system-manufacturer || true
          sudo dmidecode -s system-product-name || true
          sudo dmidecode -t bios -t system -t processor -t memory | sed -n '1,200p' || true
          sudo lshw -short || true
          lspci -nn || true
          lsusb || true

          echo "=== Storage ==="
          lsblk -o NAME,MODEL,SIZE,TYPE,MOUNTPOINT,FSTYPE || true
          df -h || true

          echo "=== Network ==="
          echo "${HTTP_PROXY:-}"
          ip addr show || true
          ip route || true
          ip -s link || true
          ifconfig || true

          echo "=== Cgroups ==="
          stat -fc %T /sys/fs/cgroup || true

          echo "=== Uptime and Load ==="
          uptime || true
          who -b || true
          top -b -n1 | head -n 10 || true
          cat /proc/loadavg || true
          awk '{printf "Uptime (seconds): %s\n", $1}' /proc/uptime 2>/dev/null || true
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          set -x
          echo "=== Kernel and OS ==="
          uname -a || true
          systeminfo || true
          wmic os get Caption,Version,BuildNumber /value || true

          echo "=== CPU ==="
          wmic cpu get Name,NumberOfCores,NumberOfLogicalProcessors /value || true
          wmic cpu get VirtualizationFirmwareEnabled,SecondLevelAddressTranslationExtensions /value || true
          powershell.exe -NoProfile -Command "Get-CimInstance Win32_Processor | Select-Object Name,Manufacturer,SocketDesignation,MaxClockSpeed | Format-List" || true

          echo "=== Memory ==="
          systeminfo | findstr /C:\"Total Physical Memory\" /C:\"Available Physical Memory\" || true
          wmic OS get TotalVisibleMemorySize,FreePhysicalMemory /value || true
          powershell.exe -NoProfile -Command "Get-CimInstance Win32_PhysicalMemory | Select-Object Manufacturer,PartNumber,Capacity,Speed | Format-Table -AutoSize" || true

          echo "=== Virtualization ==="
          systeminfo | findstr /C:\"Virtualization\" || true
          powershell.exe -NoProfile -Command "Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-All" || true

          echo "=== Hardware Inventory ==="
          wmic computersystem get Manufacturer,Model,SystemType,TotalPhysicalMemory /value || true
          powershell.exe -NoProfile -Command "Get-CimInstance Win32_BaseBoard | Format-List Manufacturer,Product,SerialNumber" || true
          powershell.exe -NoProfile -Command "Get-CimInstance Win32_BIOS | Format-List Manufacturer,SMBIOSBIOSVersion,ReleaseDate" || true

          echo "=== Storage ==="
          wmic logicaldisk get Name,FileSystem,FreeSpace,Size,VolumeName /value || true
          powershell.exe -NoProfile -Command "Get-PhysicalDisk | Select FriendlyName,Model,SerialNumber,MediaType,Size,BusType | Format-Table -AutoSize" || true
          powershell.exe -NoProfile -Command "Get-Volume | Select-Object DriveLetter,FileSystemLabel,FileSystem,SizeRemaining,Size | Format-Table -AutoSize" || true

          echo "=== Network ==="
          echo "${HTTP_PROXY:-}"
          ipconfig /all || true
          route print || true
          netstat -rn || true
          powershell.exe -NoProfile -Command "Get-NetAdapter | Format-Table -AutoSize" || true
          powershell.exe -NoProfile -Command "Get-DnsClientServerAddress | Format-Table -AutoSize" || true

          echo "=== Uptime and Load ==="
          net stats srv || true
          powershell.exe -NoProfile -Command "(Get-CimInstance win32_operatingsystem).LastBootUpTime" || true
          powershell.exe -NoProfile -Command "Get-Counter -Counter \"\\Processor(_Total)\\% Processor Time\" -SampleInterval 1 -MaxSamples 1" || true

          echo "=== Security ==="
          powershell.exe -NoProfile -Command "Get-MpComputerStatus | Select-Object AMServiceEnabled,AntivirusEnabled,BehaviorMonitorEnabled,RealTimeProtectionEnabled | Format-List" || true
          powershell.exe -NoProfile -Command "Get-BitLockerVolume | Format-Table -AutoSize" || true
        else
          echo "Unsupported runner OS: $RUNNER_OS"
        fi
