name: "Info Block"
description: "Print runner OS/hardware/network details for debugging"
author: "medyagh"
inputs:
  fail_on_error:
    description: "Set to true to fail the step if any command errors."
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Print runner details
      shell: bash
      run: bash "${GITHUB_ACTION_PATH}/scripts/info-block.sh" "${{ inputs.fail_on_error }}"
